import type { Metadata } from 'next';
import Link from 'next/link';
import LegalPage, { legalStyles as s } from '@/components/LegalPage';

// SOURCE OF RECORD: docs/terms.html in the bird-league-app repo.
// This page mirrors it. The wording below is legal text that is also shown
// in full in the app during signup. Do not edit the copy here. Edit
// docs/terms.html first, then mirror.

export const metadata: Metadata = {
  title: 'Terms of Service - Bird League',
  description:
    'The terms you agree to when you use Bird League, including eligibility, conduct, outdoor safety, and liability.',
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" meta="Last updated: August 2026" footer={<>
      <p style={{ margin: '0 0 8px' }}>
        These terms are also shown in full in the Bird League app during signup.
      </p>
      <p style={{ margin: 0 }}>
        <Link href="/privacy">Privacy Policy</Link>
        {' · '}
        <Link href="/support">Support</Link>
      </p>
    </>}>
      <h2 style={s.h2}>1. Acceptance of Terms</h2>
      <p style={s.p}>
        By creating an account or using Bird League (&quot;the App&quot;), you agree to be bound by
        these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use
        the App. Bird League is operated by Bird League LLC (&quot;we,&quot; &quot;us,&quot; or
        &quot;our&quot;).
      </p>

      <h2 style={s.h2}>2. Eligibility &amp; Age Requirements</h2>
      <p style={s.p}>
        You must be at least 13 years old to create an account. If you are between 13 and 17, you
        represent that your parent or legal guardian has reviewed and agreed to these Terms on your
        behalf. Users under 13 are not permitted to use the App. We may terminate accounts that
        violate this requirement.
      </p>

      <h2 style={s.h2}>3. Account Responsibility</h2>
      <p style={s.p}>
        You are responsible for maintaining the confidentiality of your login credentials and for
        all activity under your account. You agree to provide accurate information during
        registration and to update it as needed. We reserve the right to suspend or terminate
        accounts that provide false information or violate these Terms.
      </p>

      <h2 style={s.h2}>4. The Service</h2>
      <p style={s.p}>
        Bird League is a fantasy sports-style birdwatching application. The App allows users to
        record bird sounds for identification, log sightings, earn points, compete in leagues, and
        interact with other users. Bird identification results are generated by third-party AI
        models and are not guaranteed to be accurate. The App is provided for entertainment and
        recreational purposes only.
      </p>

      <h2 style={s.h2}>5. Assumption of Risk: Outdoor Activity</h2>
      <p style={s.p}>
        BIRD LEAGUE ENCOURAGES OUTDOOR ACTIVITY. BY USING THE APP, YOU ACKNOWLEDGE AND ACCEPT THE
        INHERENT RISKS ASSOCIATED WITH OUTDOOR RECREATION, INCLUDING BUT NOT LIMITED TO:
      </p>
      <ul style={s.ul}>
        <li style={s.li}>Physical injury from uneven terrain, falls, or environmental hazards</li>
        <li style={s.li}>
          Encounters with wildlife, insects, or plants (including venomous species)
        </li>
        <li style={s.li}>
          Exposure to weather conditions including extreme heat, cold, storms, and lightning
        </li>
        <li style={s.li}>
          Risks associated with distracted walking or navigation while using a mobile device
        </li>
        <li style={s.li}>
          Risks of entering unfamiliar areas, including but not limited to bodies of water, cliffs,
          remote areas, and areas near vehicle traffic
        </li>
      </ul>
      <p style={s.p}>
        YOU AGREE THAT YOU ARE SOLELY RESPONSIBLE FOR YOUR PERSONAL SAFETY WHILE USING THE APP. Bird
        League does not direct, supervise, or control where or how you go birding. Always be aware
        of your surroundings, obey all posted signs and local laws, and never trespass on private
        property.
      </p>

      <h2 style={s.h2}>6. User Conduct &amp; Content</h2>
      <p style={s.p}>You agree not to use the App to:</p>
      <ul style={s.ul}>
        <li style={s.li}>Post content that is threatening, harassing, defamatory, or obscene</li>
        <li style={s.li}>Impersonate another person or entity</li>
        <li style={s.li}>
          Upload content that infringes on the intellectual property rights of others
        </li>
        <li style={s.li}>Trespass on private or restricted property to log sightings</li>
        <li style={s.li}>Submit fraudulent sighting data or manipulate scoring</li>
        <li style={s.li}>
          Interfere with the operation of the App or other users&apos; enjoyment
        </li>
      </ul>
      <p style={s.p}>
        You retain ownership of content you create (photos, text). By posting content in the App,
        you grant us a non-exclusive, royalty-free, worldwide license to display, distribute, and
        use that content within the App and for promotional purposes. We may remove content that
        violates these Terms without notice.
      </p>

      <h2 style={s.h2}>7. Reporting &amp; Enforcement</h2>
      <p style={s.p}>
        You can report content or another user from within the App. We review every report. If we
        determine that content or conduct violates these Terms, we may remove the content, issue a
        warning, restrict access to features such as league chat, remove you from one or more
        leagues, or suspend or terminate your account. The action we take depends on the severity of
        the violation and whether it has happened before.
      </p>
      <p style={s.p}>
        Reports involving credible threats of harm, sexual content involving minors, or other
        illegal activity may be reported to law enforcement.
      </p>
      <p style={s.p}>
        We do not tell you the outcome of a report you file, and we do not tell a reported user who
        reported them. Blocking a user is separate from reporting: it hides their content from you
        only, does not remove them from any league you share, and does not affect standings or
        scoring.
      </p>
      <p style={s.p}>
        If you believe we acted on your account in error, contact{' '}
        <a href="mailto:birdleaguehq@gmail.com">birdleaguehq@gmail.com</a>.
      </p>

      <h2 style={s.h2}>8. Audio Recordings</h2>
      <p style={s.p}>
        The App allows you to record audio for bird identification purposes. You are solely
        responsible for ensuring that your recordings comply with all applicable laws, including
        wiretapping and eavesdropping statutes. Some states, including California, require the
        consent of all parties being recorded. Bird League is not responsible for recordings that
        capture private conversations or other non-bird audio.
      </p>

      <h2 style={s.h2}>9. Limitation of Liability</h2>
      <p style={s.p}>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, BIRD LEAGUE LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES,
        AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
        PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO PERSONAL INJURY, PROPERTY DAMAGE, LOST
        PROFITS, OR DATA LOSS, ARISING FROM OR RELATED TO YOUR USE OF THE APP.
      </p>
      <p style={s.p}>
        OUR TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THESE TERMS OR YOUR USE OF THE APP SHALL NOT
        EXCEED THE AMOUNT YOU HAVE PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE
        HUNDRED DOLLARS ($100), WHICHEVER IS GREATER.
      </p>
      <p style={s.p}>
        THE APP IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
        KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT BIRD
        IDENTIFICATION RESULTS WILL BE ACCURATE, COMPLETE, OR RELIABLE.
      </p>

      <h2 style={s.h2}>10. Indemnification</h2>
      <p style={s.p}>
        You agree to indemnify, defend, and hold harmless Bird League LLC and its officers,
        directors, employees, and agents from any claims, damages, losses, liabilities, and expenses
        (including reasonable attorneys&apos; fees) arising from your use of the App, your violation
        of these Terms, your violation of any law, or your violation of any rights of a third party.
      </p>

      <h2 style={s.h2}>11. Dispute Resolution &amp; Governing Law</h2>
      <p style={s.p}>
        These Terms are governed by the laws of the State of California, without regard to conflict
        of law principles. Any disputes arising from these Terms or your use of the App shall be
        resolved through binding arbitration administered by JAMS in San Jose, California, except
        that either party may seek injunctive relief in a court of competent jurisdiction. You agree
        to waive any right to a jury trial and to participate in a class action lawsuit against Bird
        League LLC.
      </p>

      <h2 style={s.h2}>12. Changes to Terms</h2>
      <p style={s.p}>
        We may update these Terms from time to time. We will notify you of material changes through
        the App or by email. Continued use of the App after changes take effect constitutes
        acceptance of the updated Terms.
      </p>

      <h2 style={s.h2}>13. Termination</h2>
      <p style={s.p}>
        We reserve the right to suspend or terminate your account at any time, with or without
        cause, and with or without notice. Upon termination, your right to use the App ceases
        immediately. Sections 5 through 11 survive termination.
      </p>

      <h2 style={s.h2}>14. Contact</h2>
      <p style={s.p}>
        Questions about these Terms? Contact us at{' '}
        <a href="mailto:birdleaguehq@gmail.com">birdleaguehq@gmail.com</a>.
      </p>
    </LegalPage>
  );
}
